feat(ProcessTemplate): Added and refactored process template view
blankoslo/Trak pull request #46
Opened 2021-12-23 23:09 UTC by maxschau

Closes #44 

The following has been done:

- Updated index.tsx to use the correct endpoint (so that we can fetch all employees)
- Refactored ProcessTemplate-page according to sketches, and new view.
- This page can now be used on mobile (did it simple, and removed columns as the screen gets smaller)
- Did some changes to some components because of changes in both MUI and React-hook-form (I think we have learned that we never wait so long to update our dependencies again :/ )

Screenshots:
![image](https://user-images.githubusercontent.com/49594236/147298304-b0a5b423-2f47-4eb6-9fbb-cddd88e5b75b.png)

![image](https://user-images.githubusercontent.com/49594236/147298317-c657c694-5dd8-4c18-af8b-8ff8723b11b0.png)

![image](https://user-images.githubusercontent.com/49594236/147298323-a68562a7-8eaa-49f8-b467-590913ff5dda.png)

![image](https://user-images.githubusercontent.com/49594236/147298377-2e147c51-3122-4133-99a0-149c010e4812.png)

![image](https://user-images.githubusercontent.com/49594236/147298388-ffed071b-9f84-48fa-bd04-d32ed946bd88.png)

![image](https://user-images.githubusercontent.com/49594236/147298340-e0342c38-deba-4f9c-a184-af423d50084e.png)

![image](https://user-images.githubusercontent.com/49594236/147298347-69a4f420-26d8-43d2-8b10-b214324f3349.png)

2021-12-26 18:57 UTC, Zenjjim requested changes
sykt bra jobbet. Det er hella sick ut. Kommentaren om å gjøre om til sx api for raskere MUI render er et forslag fra min side. Da må iallefall alle makeStyle og style fjernes :shipit:

2021-12-26 18:57 UTC, Zenjjim commented on package.json
> +    "month-days": "^4.0.0",
siden vi bruker date-fns kan du bruke denne metoden her. https://date-fns.org/v2.27.0/docs/getDaysInMonth

2021-12-26 18:57 UTC, Zenjjim commented on package.json
> +    "capitalize-first-letter": "^1.0.0",
kan du bytte ut denne pakken med denne: https://www.npmjs.com/package/capitalize. Ser ut som denne er mer maintained

2021-12-26 18:57 UTC, Zenjjim commented on src/components/Modal.tsx
> +const useStyles = makeStyles({
på grunn av material ui changes er det raskere og "bedre" practice å bruke sx direkte på komponenten nå. Er det en tanke å benytte seg av dette?

2021-12-26 18:57 UTC, Zenjjim commented on src/components/PageTitle.tsx
> +const useStyles = makeStyles((theme: Theme) => ({
kanskje gjøre om til sx?

2021-12-26 18:57 UTC, Zenjjim commented on src/components/form/BeforeToggle.tsx
> +const useStyles = makeStyles((theme: Theme) => ({
sx

2021-12-26 18:57 UTC, Zenjjim commented on src/components/form/BeforeToggle.tsx
> +        style={{ height: '36px' }}
sx

2021-12-26 18:57 UTC, Zenjjim commented on src/components/form/BeforeToggle.tsx
> +      <InputLabel htmlFor='select-before' style={{ display: 'none' }}>
sx

2021-12-26 18:57 UTC, Zenjjim commented on src/components/views/prosessmal/PhaseModal.tsx
> +          <div>
her er det vel greit å bruke react fragment <> fordi en ekstra div gjør bare html-treet mer rotete :D

2021-12-26 18:57 UTC, Zenjjim commented on src/components/views/prosessmal/PhaseTable.tsx
> + */
om du gidder fjern gjerne all js-doc template for det gjør legit bare filen sykt irr å lese. tar opp unødvendig plass

2021-12-26 18:57 UTC, Zenjjim commented on src/components/views/prosessmal/TaskModal.tsx
> +            //dueDate: moment().set({ month: formData.month, date: formData.day }).toDate(),
del

2021-12-26 18:57 UTC, Zenjjim commented on src/context/Data.tsx
> +import { useSession } from 'next-auth/react';
en tanke om denne filen. Er det ikke sykt waste at en bruker må loade alle mulig ansatte, tags osv når brukeren ikke skal lage en oppgave. Føler dette kun burde skje om en bruker går inn på en modal

2021-12-26 18:57 UTC, Zenjjim commented on src/context/Data.tsx
> +  const { data: tags } = useSWR(session?.user ? `/api/tags` : null, fetcher);
hva er tanken om tags?? skal det fortsatt brukes for i designet er det ganske utelatt

2021-12-26 18:57 UTC, Zenjjim commented on src/pages/api/allEmployees.ts
> +import HttpStatusCode from 'http-status-typed';
gjorde om /api/employees til dette apiet. så denne filen kan slettes

2021-12-26 18:57 UTC, Zenjjim commented on src/utils/utils.ts
> +export const getMonths = () => {
😆

2021-12-29 11:16 UTC, maxschau commented on src/pages/api/allEmployees.ts
> +import HttpStatusCode from 'http-status-typed';
Nei, dette er et ekstra endepunkt jeg behøvde til å hente ut alle ansatte i oversikt-over-ansatt-siden. Måtte vike litt fra REST-prinsippet, men it is what it is. 

Du hadde slettet den når du fjernet det gamle designet fant jeg ut, og da hentet den aldri ut "alle ansatte" pga. feil endepunkt.

2021-12-29 11:19 UTC, maxschau commented on src/components/Modal.tsx
> +const useStyles = makeStyles({
Vi kan godt gjøre det, men da synes jeg det skal bli et eget issue, og dermed en egen PR. 
Det fungerer helt fint sånn som det er nå, og er ikke noe jeg synes vi burde bruke masse tid på før vi har fått gjort ferdig den opprinnelige planen om nytt design.

2021-12-29 11:20 UTC, maxschau commented on src/components/Modal.tsx
> +const useStyles = makeStyles({
Lager et issue på det nå #47

2021-12-29 11:31 UTC, maxschau commented on src/context/Data.tsx
> +import { useSession } from 'next-auth/react';
"sykt waste" er vel litt å ta i. Det er snakk om 223 B + 223 B + 225B = 671B som blir hentet ut 1 gang når man går inn på prosessmal. Ettersom vi bruker SWR vil dette bli cachet, og dermed vil man benytte den samme dataen for alle fasene og alle oppgavene istedenfor å hente ut på nytt for hver task/fase. 

Hvorvidt dette er sykt waste er jeg ekstremt usikker på, og jeg føler at dette gjør det såpass enkelt for de andre komponentente at det egentlig trumfer det at vi gjør en potensielt unødvendig initiell spørring.

2021-12-29 11:32 UTC, maxschau commented on src/context/Data.tsx
> +  const { data: tags } = useSWR(session?.user ? `/api/tags` : null, fetcher);
Vi har ikke tatt en vurdering på det med de andre. Tenker vi kan høre med resten, og så eventuelt fjerne det.

2021-12-29 11:45 UTC, Zenjjim commented on src/context/Data.tsx
> +import { useSession } from 'next-auth/react';
Ja enig at den burde være der og beholde metoden den gjør det på. Men atm så slår denne ut når vi går logger inn. Tanken min er at istedenfor så kjøres denne uthentingen og cachingen når man går inn på prosessmal siden. Og dersom en bruker bare logger inn for å se hvilken oppgaven hen gå gjøre så trengs ikke denne dataen

2021-12-29 11:50 UTC, Zenjjim commented on src/context/Data.tsx
> +import { useSession } from 'next-auth/react';
Nei ser hva du har gjort. Enig med løsning ja 😅

2021-12-29 12:00 UTC, merged